"""Install a real `Seaglass.app` bundle into ~/Applications.

Everything else about this app is already native-feeling -- window,
icon, name -- but it can only be started from a terminal, and a
terminal-launched interpreter is a second-class citizen on macOS: it is
not in Spotlight, it can't be pinned to the Dock across restarts, and
its identity has to be patched at runtime (see `_set_macos_app_name`).

A bundle fixes all of that at the source rather than in workarounds. The
bundle is a thin wrapper around this checkout's `seaglass-app`, so there
is exactly one installation of the code and `git pull` keeps the app up
to date with no reinstall step.

The bundle executable has to be a compiled binary, not a shell script:
current macOS refuses to launch a bundle whose CFBundleExecutable is a
script (`_LSOpenURLsWithCompletionHandler ... error -10669`), however
common that trick used to be. So a ~10-line C stub is compiled at install
time and it execs the readable launch script next to it.
"""
from __future__ import annotations

import os
import plistlib
import shutil
import stat
import subprocess
from pathlib import Path

APP_NAME = "Seaglass"
BUNDLE_ID = "dev.seaglass.app"


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def default_destination() -> Path:
    return Path.home() / "Applications" / f"{APP_NAME}.app"


def _launcher_script(venv_bin: Path) -> str:
    home = "${SEAGLASS_HOME:-$HOME/.seaglass}"
    return f"""#!/bin/bash
# Generated by `python -m seaglass.app.installapp` -- do not edit; it is
# overwritten on reinstall. Points at the checkout it was generated from.
set -euo pipefail
SEAGLASS_HOME="{home}"
mkdir -p "$SEAGLASS_HOME"
exec "{venv_bin}/seaglass-app" \\
  --index-db "$SEAGLASS_HOME/index.db" \\
  --chat-db "$SEAGLASS_HOME/chat_snapshot.db" \\
  --chat-db-source "${{SEAGLASS_CHAT_DB_SRC:-$HOME/Library/Messages/chat.db}}"
"""


_STUB_C = """#include <unistd.h>
/* Generated by seaglass.app.installapp. Bundle executables must be Mach-O
   binaries -- a shell script here fails to launch with LaunchServices
   error -10669 -- so this exists only to exec the real launch script. */
int main(int argc, char **argv) {
    (void)argc; (void)argv;
    execl("%(script)s", "%(script)s", (char *)0);
    return 1;
}
"""


def _compile_stub(destination: Path, script: Path) -> None:
    source = destination.parent / "_stub.c"
    source.write_text(_STUB_C % {"script": str(script)})
    try:
        subprocess.run(
            ["clang", "-O1", "-o", str(destination), str(source)],
            check=True,
            capture_output=True,
        )
    except FileNotFoundError:
        raise SystemExit(
            "clang not found -- install the Xcode command line tools "
            "(`xcode-select --install`) and re-run, or just use ./start.sh"
        )
    except subprocess.CalledProcessError as exc:
        raise SystemExit(f"failed to build the app stub: {exc.stderr.decode().strip()}")
    finally:
        source.unlink(missing_ok=True)


def install(destination: Path | None = None, venv_bin: Path | None = None) -> Path:
    """Write (or replace) the bundle. Returns the bundle path."""
    root = repo_root()
    venv_bin = venv_bin or (root / ".venv" / "bin")
    if not (venv_bin / "seaglass-app").exists():
        raise SystemExit(
            f"no seaglass-app executable at {venv_bin}/seaglass-app -- run ./setup.sh first"
        )

    bundle = destination or default_destination()
    contents = bundle / "Contents"
    macos = contents / "MacOS"
    resources = contents / "Resources"

    # Replaced wholesale rather than merged: a stale executable left behind
    # by an older layout would silently keep launching.
    if bundle.exists():
        shutil.rmtree(bundle)
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    script = resources / "launch.sh"
    script.write_text(_launcher_script(venv_bin))
    script.chmod(script.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    _compile_stub(macos / APP_NAME, script)

    icon = root / "seaglass" / "app" / "static" / "icons" / "seaglass.icns"
    icon_file = None
    if icon.exists():
        shutil.copyfile(icon, resources / "seaglass.icns")
        icon_file = "seaglass"

    info = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleExecutable": APP_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundlePackageType": "APPL",
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundleShortVersionString": "1.0",
        "CFBundleVersion": "1.0",
        # Without this the window opens behind everything and the app has
        # no menu bar of its own.
        "LSUIElement": False,
        "NSHighResolutionCapable": True,
        "NSAppleEventsUsageDescription": "Seaglass reads your local Messages database to search it.",
        # Without this key macOS refuses the Contacts prompt outright -- it
        # flashes on screen and vanishes, leaving no way to grant access,
        # since System Settings only lists apps that have already asked.
        "NSContactsUsageDescription": "Seaglass uses your contacts to show names instead of phone numbers in search results.",
    }
    if icon_file:
        info["CFBundleIconFile"] = icon_file
    with (contents / "Info.plist").open("wb") as handle:
        plistlib.dump(info, handle)

    # Ad-hoc sign the finished bundle. The privacy system identifies an app
    # by its signature, so an unsigned or stale-signed bundle can have its
    # grants quietly dropped. This must run after the Info.plist is written,
    # since the signature seals it.
    os.system(f"codesign --force --sign - {str(bundle)!r} >/dev/null 2>&1 || true")

    # Nudge LaunchServices so Spotlight/the Dock pick it up immediately
    # instead of whenever it next rescans.
    os.system(
        "/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework"
        f"/Support/lsregister -f {str(bundle)!r} >/dev/null 2>&1 || true"
    )
    return bundle


def main() -> int:
    bundle = install()
    print(f"Installed {bundle}")
    print("Launch it from Spotlight or the Applications folder, and keep it in the Dock.")
    print()
    # macOS scopes privacy grants per app identity, so the bundle starts
    # with none of the access the terminal had. Without this warning the
    # symptoms look like bugs: every sender shows as a raw phone number and
    # the app insists the index is up to date forever.
    print("First launch will need permissions granted to Seaglass itself --")
    print("terminal launches inherited Terminal's, but the app is a separate identity:")
    print("  System Settings > Privacy & Security > Full Disk Access  -> enable Seaglass")
    print("  System Settings > Privacy & Security > Contacts          -> enable Seaglass")
    print("The app says so in its status bar if either is missing.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
